create table springproject.employee (id  bigserial not null, cpf varchar(255), name varchar(255), password varchar(255), profile varchar(255), registration varchar(255), status varchar(255), primary key (id))
create table springproject.vehicle (id  bigserial not null, chassi varchar(255), id_integr varchar(255), tracker_brand varchar(255), tracker_version varchar(255), primary key (id))
create table springproject.employee (id  bigserial not null, cpf varchar(255), name varchar(255), password varchar(255), profile varchar(255), registration varchar(255), status varchar(255), primary key (id))
create table springproject.vehicle (id  bigserial not null, chassi varchar(255), id_integr varchar(255), tracker_brand varchar(255), tracker_version varchar(255), primary key (id))
create table springproject.employee (id  bigserial not null, cpf varchar(255), name varchar(255), password varchar(255), profile varchar(255), registration varchar(255), status varchar(255), primary key (id))
create table springproject.vehicle (id  bigserial not null, chassi varchar(255), id_integr varchar(255), tracker_brand varchar(255), tracker_version varchar(255), primary key (id))
create table springproject.employee (id  bigserial not null, cpf varchar(255), name varchar(255), password varchar(255), profile varchar(255), registration varchar(255), status varchar(255), primary key (id))
create table springproject.vehicle (id  bigserial not null, chassi varchar(255), id_integr varchar(255), tracker_brand varchar(255), tracker_version varchar(255), primary key (id))
create table springproject.employee (id  bigserial not null, cpf varchar(255), name varchar(255), password varchar(255), profile varchar(255), registration varchar(255), status varchar(255), primary key (id))
create table springproject.vehicle (id  bigserial not null, chassi varchar(255), id_integr varchar(255), tracker_brand varchar(255), tracker_version varchar(255), primary key (id))
create table springproject.employee (id  bigserial not null, cpf varchar(255), name varchar(255), password varchar(255), profile varchar(255), registration varchar(255), status varchar(255), primary key (id))
create table springproject.vehicle (id  bigserial not null, chassi varchar(255), id_integr varchar(255), tracker_brand varchar(255), tracker_version varchar(255), primary key (id))
create table springproject.employee (id  bigserial not null, cpf varchar(255), name varchar(255), password varchar(255), profile varchar(255), registration varchar(255), status varchar(255), primary key (id))
create table springproject.vehicle (id  bigserial not null, chassi varchar(255), id_integr varchar(255), tracker_brand varchar(255), tracker_version varchar(255), primary key (id))
create table springproject.employee (id  bigserial not null, cpf varchar(255), name varchar(255), password varchar(255), profile varchar(255), registration varchar(255), status varchar(255), primary key (id))
create table springproject.vehicle (id  bigserial not null, chassi varchar(255), id_integr varchar(255), tracker_brand varchar(255), tracker_version varchar(255), primary key (id))
create table springproject.employee (id  bigserial not null, cpf varchar(255), name varchar(255), password varchar(255), profile varchar(255), registration varchar(255), status varchar(255), primary key (id))
create table springproject.vehicle (id  bigserial not null, chassi varchar(255), id_integr varchar(255), tracker_brand varchar(255), tracker_version varchar(255), primary key (id))
create table springproject.employee (id  bigserial not null, cpf varchar(255), name varchar(255), password varchar(255), profile varchar(255), registration varchar(255), status varchar(255), primary key (id))
create table springproject.vehicle (id  bigserial not null, chassi varchar(255), id_integr varchar(255), tracker_brand varchar(255), tracker_version varchar(255), primary key (id))
create table springproject.employee (id  bigserial not null, cpf varchar(255), name varchar(255), password varchar(255), profile varchar(255), registration varchar(255), status varchar(255), primary key (id))
create table springproject.vehicle (id  bigserial not null, chassi varchar(255), id_integr varchar(255), tracker_brand varchar(255), tracker_version varchar(255), primary key (id))
create table springproject.employee (id  bigserial not null, cpf varchar(255), name varchar(255), password varchar(255), profile varchar(255), registration varchar(255), status varchar(255), primary key (id))
create table springproject.vehicle (id  bigserial not null, chassi varchar(255), id_integr varchar(255), tracker_brand varchar(255), tracker_version varchar(255), primary key (id))
create table springproject.employee (id  bigserial not null, cpf varchar(255), name varchar(255), password varchar(255), profile varchar(255), registration varchar(255), status varchar(255), primary key (id))
create table springproject.vehicle (id  bigserial not null, chassi varchar(255), id_integr varchar(255), tracker_brand varchar(255), tracker_version varchar(255), primary key (id))
create table springproject.employee (id  bigserial not null, cpf varchar(255), name varchar(255), password varchar(255), profile varchar(255), registration varchar(255), status varchar(255), primary key (id))
create table springproject.vehicle (id  bigserial not null, chassi varchar(255), id_integr varchar(255), tracker_brand varchar(255), tracker_version varchar(255), primary key (id))
create table springproject.employee (id  bigserial not null, cpf varchar(255), name varchar(255), password varchar(255), profile varchar(255), registration varchar(255), status varchar(255), primary key (id))
create table springproject.vehicle (id  bigserial not null, chassi varchar(255), id_integr varchar(255), tracker_brand varchar(255), tracker_version varchar(255), primary key (id))
create table springproject.employee (id  bigserial not null, cpf varchar(255), name varchar(255), password varchar(255), profile varchar(255), registration varchar(255), status varchar(255), primary key (id))
create table springproject.vehicle (id  bigserial not null, chassi varchar(255), id_integr varchar(255), tracker_brand varchar(255), tracker_version varchar(255), primary key (id))
create table springproject.employee (id  bigserial not null, cpf varchar(255), name varchar(255), password varchar(255), profile varchar(255), registration varchar(255), status varchar(255), primary key (id))
create table springproject.vehicle (id  bigserial not null, chassi varchar(255), id_integr varchar(255), tracker_brand varchar(255), tracker_version varchar(255), primary key (id))
create table springproject.employee (id  bigserial not null, cpf varchar(255), name varchar(255), password varchar(255), profile varchar(255), registration varchar(255), status varchar(255), primary key (id))
create table springproject.vehicle (id  bigserial not null, chassi varchar(255), id_integr varchar(255), tracker_brand varchar(255), tracker_version varchar(255), primary key (id))
create table springproject.employee (id  bigserial not null, cpf varchar(255), name varchar(255), password varchar(255), profile varchar(255), registration varchar(255), status varchar(255), primary key (id))
create table springproject.vehicle (id  bigserial not null, chassi varchar(255), id_integr varchar(255), tracker_brand varchar(255), tracker_version varchar(255), primary key (id))
create table springproject.employee (id  bigserial not null, cpf varchar(255), name varchar(255), password varchar(255), profile varchar(255), registration varchar(255), status varchar(255), primary key (id))
create table springproject.vehicle (id  bigserial not null, chassi varchar(255), id_integr varchar(255), tracker_brand varchar(255), tracker_version varchar(255), primary key (id))
create table springproject.employee (id  bigserial not null, cpf varchar(255), name varchar(255), password varchar(255), profile varchar(255), registration varchar(255), status varchar(255), primary key (id))
create table springproject.vehicle (id  bigserial not null, chassi varchar(255), id_integr varchar(255), tracker_brand varchar(255), tracker_version varchar(255), primary key (id))
create table springproject.employee (id  bigserial not null, cpf varchar(255), name varchar(255), password varchar(255), profile varchar(255), registration varchar(255), status varchar(255), primary key (id))
create table springproject.vehicle (id  bigserial not null, chassi varchar(255), id_integr varchar(255), tracker_brand varchar(255), tracker_version varchar(255), primary key (id))
